package app;

import java.text.NumberFormat;
import javax.swing.JFileChooser;

public class MainFrame extends javax.swing.JFrame {

    public MainFrame() {
        intFormat = NumberFormat.getIntegerInstance();
        intFormat.setGroupingUsed(false);
        
        initComponents();
        this.wybierzPlik = new JFileChooser();
        this.appLogic = new GrafAnalizer();
    }
    
    // funkcje zmieniajace wyswietlenie - operacje w okienku
    
    void wlaczPanelAnalizuj(){
        osiagalnoscButton.setEnabled(true);
        cyklButton.setEnabled(true);
        odField.setEnabled(true);
        doField.setEnabled(true);
        startField.setEnabled(true);
        zapiszButton.setEnabled(true);
    }
    
    void wyswietlGraf(){
        mainTextArea.setText(appLogic.wyswietlGraf());
        infoField.setText("Graf:");
        wlaczPanelAnalizuj();
    }
    
    void wyswietlOsiagalnoscCNF(int odStanu, int doStanu){
        mainTextArea.setText(appLogic.wyswietlOsiagalnoscCNF(odStanu, doStanu));
        infoField.setText(String.format("Formuła CNF: osiagalność dla (%d -> %d)", odStanu, doStanu));
    }

    void wyswietlCyklCNF(int odStanu){
        mainTextArea.setText(appLogic.wyswietlCyklCNF(odStanu));
        infoField.setText(String.format("Formuła CNF: cykl od stanu %d", odStanu));
    }
    
    // ---------------------------

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mainTextArea = new javax.swing.JTextArea();
        grafEditPanel = new javax.swing.JPanel();
        nowyGrafButton = new javax.swing.JButton();
        losujGrafButton = new javax.swing.JButton();
        grafLabel = new javax.swing.JLabel();
        wgrajGrafButton = new javax.swing.JButton();
        zapiszButton = new javax.swing.JButton();
        analizujPanel = new javax.swing.JPanel();
        analizujLabel = new javax.swing.JLabel();
        osiagalnoscButton = new javax.swing.JButton();
        odField = new javax.swing.JFormattedTextField(intFormat);
        doField = new javax.swing.JFormattedTextField(intFormat);
        doLabel = new javax.swing.JLabel();
        odLabel = new javax.swing.JLabel();
        cyklButton = new javax.swing.JButton();
        startField = new javax.swing.JFormattedTextField(intFormat);
        startLabel = new javax.swing.JLabel();
        infoField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainTextArea.setEditable(false);
        mainTextArea.setColumns(20);
        mainTextArea.setRows(5);
        jScrollPane1.setViewportView(mainTextArea);

        grafEditPanel.setName(""); // NOI18N

        nowyGrafButton.setText("Nowy");
        nowyGrafButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nowyGrafButtonActionPerformed(evt);
            }
        });

        losujGrafButton.setText("Losuj");
        losujGrafButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                losujGrafButtonActionPerformed(evt);
            }
        });

        grafLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        grafLabel.setText("Graf");

        wgrajGrafButton.setText("Wgraj");
        wgrajGrafButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wgrajGrafButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout grafEditPanelLayout = new javax.swing.GroupLayout(grafEditPanel);
        grafEditPanel.setLayout(grafEditPanelLayout);
        grafEditPanelLayout.setHorizontalGroup(
            grafEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grafEditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(grafLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(grafEditPanelLayout.createSequentialGroup()
                .addGroup(grafEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(grafEditPanelLayout.createSequentialGroup()
                        .addComponent(nowyGrafButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wgrajGrafButton))
                    .addComponent(losujGrafButton))
                .addGap(0, 34, Short.MAX_VALUE))
        );
        grafEditPanelLayout.setVerticalGroup(
            grafEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grafEditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(grafLabel)
                .addGap(7, 7, 7)
                .addGroup(grafEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nowyGrafButton)
                    .addComponent(wgrajGrafButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(losujGrafButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        zapiszButton.setText("Zapisz");
        zapiszButton.setEnabled(false);
        zapiszButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zapiszButtonActionPerformed(evt);
            }
        });

        analizujLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        analizujLabel.setText("Analizuj");

        osiagalnoscButton.setText("Osiągalność");
        osiagalnoscButton.setEnabled(false);
        osiagalnoscButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osiagalnoscButtonActionPerformed(evt);
            }
        });

        odField.setEnabled(false);

        doField.setEnabled(false);

        doLabel.setText("do");

        odLabel.setText("od");

        cyklButton.setText("Cykl");
        cyklButton.setEnabled(false);
        cyklButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cyklButtonActionPerformed(evt);
            }
        });

        startField.setEnabled(false);

        startLabel.setText("start");

        javax.swing.GroupLayout analizujPanelLayout = new javax.swing.GroupLayout(analizujPanel);
        analizujPanel.setLayout(analizujPanelLayout);
        analizujPanelLayout.setHorizontalGroup(
            analizujPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(analizujPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(analizujPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(analizujPanelLayout.createSequentialGroup()
                        .addGroup(analizujPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(analizujLabel)
                            .addGroup(analizujPanelLayout.createSequentialGroup()
                                .addComponent(odLabel)
                                .addGap(4, 4, 4)
                                .addComponent(odField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(doLabel)
                                .addGap(4, 4, 4)
                                .addComponent(doField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(analizujPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(startLabel)
                        .addGap(4, 4, 4)
                        .addComponent(startField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(analizujPanelLayout.createSequentialGroup()
                .addGroup(analizujPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(osiagalnoscButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cyklButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        analizujPanelLayout.setVerticalGroup(
            analizujPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(analizujPanelLayout.createSequentialGroup()
                .addComponent(analizujLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(osiagalnoscButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(analizujPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(odField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(odLabel)
                    .addComponent(doLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cyklButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(analizujPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        infoField.setEditable(false);
        infoField.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(zapiszButton))
                    .addComponent(infoField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(grafEditPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(analizujPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zapiszButton))
            .addGroup(layout.createSequentialGroup()
                .addComponent(grafEditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(analizujPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // ------------ Przyciski - Akcje
    
    private void nowyGrafButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nowyGrafButtonActionPerformed
        NowyGrafDialog nowyDialog = new NowyGrafDialog(this, rootPaneCheckingEnabled);
        nowyDialog.setVisible(true);
        if(nowyDialog.getReturnStatus() == NowyGrafDialog.RET_OK){
            System.out.println("NowyGraf: ok -> stworz nowy graf");
            if(appLogic.nowyGrafzTekstu(nowyDialog.getResult())){
                wyswietlGraf();
            }
        }
    }//GEN-LAST:event_nowyGrafButtonActionPerformed

    private void zapiszButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zapiszButtonActionPerformed
        // wyswietl wybieranie pliku
        int rVal = wybierzPlik.showOpenDialog(this);
        if (rVal == JFileChooser.APPROVE_OPTION) { // wybrany
            String sciezka = wybierzPlik.getSelectedFile().getPath();
            System.out.println("Zapis do " + sciezka);
            if(appLogic.zapiszTekstDoPliku(mainTextArea.getText(), sciezka)){
                infoField.setText("Zapisano do pliku: " + wybierzPlik.getSelectedFile().getName());
            }
        } else if(rVal == JFileChooser.CANCEL_OPTION) {
            System.out.println("cancel");
        }
    }//GEN-LAST:event_zapiszButtonActionPerformed

    private void osiagalnoscButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osiagalnoscButtonActionPerformed
        System.out.println("Osiagalnosc");
        int odStanu = Integer.parseInt(odField.getText());
        int doStanu = Integer.parseInt(doField.getText());
        wyswietlOsiagalnoscCNF(odStanu, doStanu);
    }//GEN-LAST:event_osiagalnoscButtonActionPerformed

    private void losujGrafButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_losujGrafButtonActionPerformed
        LosujGrafDialog losujDialog = new LosujGrafDialog(this, rootPaneCheckingEnabled);
        losujDialog.setVisible(true);
        if(losujDialog.getReturnStatus() == LosujGrafDialog.RET_OK){
            System.out.println("LosujGraf: ok -> losuj nowy graf");
            int stany = losujDialog.getLiczbaStanow();
            int tranzycje = losujDialog.getLiczbaTranzycji();
            if(appLogic.nowyGrafLosowy(stany, tranzycje)){
                wyswietlGraf();
            }
        }
    }//GEN-LAST:event_losujGrafButtonActionPerformed

    private void cyklButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cyklButtonActionPerformed
        System.out.println("Cykl");
        int odStanu = Integer.parseInt(startField.getText());
        wyswietlCyklCNF(odStanu);
    }//GEN-LAST:event_cyklButtonActionPerformed

    private void wgrajGrafButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wgrajGrafButtonActionPerformed
        // wyswietl wybieranie pliku
        int rVal = wybierzPlik.showOpenDialog(this);
        if (rVal == JFileChooser.APPROVE_OPTION) { // wybrany
            String sciezka = wybierzPlik.getSelectedFile().getPath();
            System.out.println("Wczytaj graf z: " + sciezka);
            if(appLogic.nowyGrafzPliku(sciezka)){
                wyswietlGraf();
                infoField.setText("Wczytano z pliku: " + wybierzPlik.getSelectedFile().getName());
            }
        } else if(rVal == JFileChooser.CANCEL_OPTION) {
            System.out.println("cancel");
        }
    }//GEN-LAST:event_wgrajGrafButtonActionPerformed

    // ------------ Uruchomienie
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    // ------------ Komponenty
    
    private final GrafAnalizer appLogic;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel analizujLabel;
    private javax.swing.JPanel analizujPanel;
    private javax.swing.JButton cyklButton;
    private javax.swing.JTextField doField;
    private javax.swing.JLabel doLabel;
    private javax.swing.JPanel grafEditPanel;
    private javax.swing.JLabel grafLabel;
    private javax.swing.JTextField infoField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton losujGrafButton;
    private javax.swing.JTextArea mainTextArea;
    private javax.swing.JButton nowyGrafButton;
    private javax.swing.JTextField odField;
    private javax.swing.JLabel odLabel;
    private javax.swing.JButton osiagalnoscButton;
    private javax.swing.JTextField startField;
    private javax.swing.JLabel startLabel;
    private javax.swing.JButton wgrajGrafButton;
    private javax.swing.JButton zapiszButton;
    // End of variables declaration//GEN-END:variables
    private final JFileChooser wybierzPlik;
    private final NumberFormat intFormat;
}
